
enableGlobalCache: false

enableTelemetry: false

yarnPath: .yarn/releases/yarn-3.5.0.cjs

nmMode: hardlinks-local

nodeLinker: node-modules

logFilters:
  - code: YN0013
    level: discard
  - code: YN0005
    level: discard
  - code: YN0060
    level: warning
  - code: YN0002
    level: warning
  - level: discard
    pattern: "*@npm:* The darwin-* architecture"

preferInteractive: true
